# Generated by Django 5.0.4 on 2024-06-25 09:03

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/home/saransh.sharma/Downloads/LinkedInPOC/backend/static/Screenshot_from_2024-05-21_18-01-17.png', upload_to=apps.user.models.user_image),
        ),
    ]
